### ISSUE TITLE
regular runs of deployment test

### ISSUE THREAD

**Issue by rruefenacht** [MeteoSwiss/mwr_raw2l1#5]
Once issue #4 is fixed, schedule regular runs of deployment tests, so that dependency problems are detected timely, when old logs from working tests are still available and changes in dependency versions cencern only a few packages. I propose to run this weekly each Monday morning by adding the a schedule statement to the "on:" section in the head of .github/workflows/CI_tests.yaml so that it reads like that:

```
on:
  schedule:
    - cron: '0 4 * * 1'
  push:
    branches:
      - master
  pull_request:
```
